// Writes util/nav.generated.json from _nav/ (runs as `prebuild` and `predev`).
//
// This file exists because of one constraint: `components/layout.js` renders on
// every page and therefore ships to the browser, so it cannot read the
// filesystem. The nav has to arrive as data.
//
// The alternative was returning the links from `getStaticProps` on all
// thirteen pages and threading them through Layout. That works, but it puts the
// same four lines in every page file and makes "the nav disappeared" the
// failure mode for forgetting them in a new one. Generating the list once, the
// way the sitemap already is, keeps it in a single place.
//
// The cost is that `next dev` reads this at import time: edit a file in _nav/
// while the dev server is running and you need to restart it to see the change.
// Production is never stale — Netlify runs a clean build, and prebuild runs
// first.
//
// This is also where the route-collision check runs, so a slug that could never
// render fails the build here with an explanation rather than silently going
// missing. See RESERVED_SLUGS in util/navPages.mjs.

import fs from "fs";
import path from "path";
import {
  getAllNavPages,
  navLinks,
  assertRoutable,
  pageRoutesFrom,
} from "../util/navPages.mjs";
import { contentDirsFromEnv } from "../util/contentFiles.mjs";

const { navDir } = contentDirsFromEnv();
const PAGES_DIR = path.join(process.cwd(), "pages");
const OUT_FILE = path.join(process.cwd(), "util", "nav.generated.json");

const pages = getAllNavPages(fs, navDir);

assertRoutable(
  pages.map((page) => page.slug),
  pageRoutesFrom(PAGES_DIR, fs)
);

const links = navLinks(pages);

fs.writeFileSync(
  OUT_FILE,
  `${JSON.stringify(
    {
      // Stated in the file itself, because it lands in an editor eventually and
      // hand-edits to it are erased by the next build.
      $comment:
        "Generated by scripts/generate-nav.mjs from _nav/. Do not edit; edit the Markdown.",
      links,
    },
    null,
    2
  )}\n`
);

console.log(
  `Generated nav with ${links.length} links (${pages.length} section pages) -> ${OUT_FILE}`
);
